### ISSUE TITLE
dcat Dataset vs dcat Distribution / dcat Data Service

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-io#19]
It seems to me that Dataset would never be the actual source, since it is an abstract description of a dataset. The source will always be a specific distribution, or a data service. So shouldn't that be the direct source that is linked to in the mapping?

A dcat dataset could have many distributions for example.

```turtle
ex:dataset1 a dcat:Dataset ;
    dcat:distribution ex:distribution1 , ex:distribution 2, ex:distribution3 ;

ex:distribution1 dcat:accessUrl <https://foo.bar/1> .
ex:distribution2 dcat:accessUrl <https://foo.bar/2> .
ex:distribution3 dcat:accessUrl <https://foo.bar/3> .
```

With this mapping:

```turtle
ex:Source a rml:Source ;
  rml:access ex:dataset1 ;
```

You don't know which of the distributions is intended.

**Comment by DylanVanAssche** [comment]
Hmmmm that's actually true... We would need to change this to DCAT Distribution which contains all the properties we need anyway

**Comment by bjdmeest** [comment]
https://kg-construct.github.io/rml-io/spec/docs/#language-map still contains a dcat:Dataset, is that intended?

**Comment by DylanVanAssche** [comment]
That's a typo... This should have been removed in 4bd56ca
