### ISSUE TITLE
How to access a local file via path relative to mapping file?

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/rml-io#36]
The mentioned DCAT spec does not allow to refer to relative file paths (it allows for relative resources, but this is relative to the @base of the RML mapping file which is not what I mean).

What would the description of the file `./data/input.json`, (path relative to the mapping file) look like?

(you could rephrase my question to 'relative to the cwd' if that makes things easier, I can always set my cwd to the mapping file folder).

**Comment by DylanVanAssche** [comment]
> does not allow to refer to relative file paths

DCAT points to URI which is RFC 3986.
[Section 4.1](https://www.rfc-editor.org/rfc/rfc3986#section-4.1) deals with relative references and [section 5](https://www.rfc-editor.org/rfc/rfc3986#section-5) explains how to resolve it to an absolute one. The algorithm talks about a base IRI indeed. This might clash with `@base` of the RML mapping.

However, I don't see how the `@base` of mapping rules are related to the source/target DCAT access description.
Either we find a solution for setting the base IRI used to resolve the DCAT access description, or a complete additional access description must be used to deal with relative paths. Happy to hear your thoughts!

**Comment by bjdmeest** [comment]
DCAT only allows resources, so relative paths using DCAT would always be a mess with @base etc.

Suggestion:

Create a `rml:RelativePathSource` which is a subclass of `rml:Source`, with two properties: `rml:path` (exactly 1) and `rml:root` (0 or 1). Also, introduce 2 constants `rml:CWD` and `rml:MappingDirectory`.

Definitions:
- `rml:path` a string that specifies a relative file path. (this could actually also be an absolute path, but then you could just as well use DCAT)
- `rml:root`: a string, rml:CWD or rml:MappingDirectory, that specifies an absolute path. The `rml:path` string will be resolved relative to this root path. By default, this is `rml:CWD`: the current working directory. Alternatively, you could specify `rml:MappingDirectory`, meaning that you resolve the `rml:path` string relative to the current mapping file (if that path exists, otherwise you default back to the cwd). (note that engines could allow to specify the cwd in their configuration)
