### ISSUE TITLE
Some possible minor issues

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-io#46]
- [x] http://w3id.org/rml/resources/Friends.json.zip resolves to the documentation --> moved to https://github.com/kg-construct/rml-resources/issues/5
- [x] 3.2.2 Compression formats refers to `rml:tarXz` and `rml:tarGz`, but rest of documentation and tests use `rml:tarxz` and `rml:targz`

**Comment by DylanVanAssche** [comment]
>  http://w3id.org/rml/resources/Friends.json.zip resolves to the documentation

Redirections seems to fail here :(
This URL should work: https://kg-construct.github.io/rml-resources/resources/Friends.json.zip
I don't know why it doesn't work, all other extensions like `.json.tar.xz` do work...

> 3.2.2 Compression formats refers to rml:tarXz and rml:tarGz, but rest of documentation and tests use rml:tarxz and rml:targz

That's a typo, it was changed in the latest revisions to all lower case, forgot it there...

**Comment by DylanVanAssche** [comment]
Fixed 3.2.2 in `main`

**Comment by DylanVanAssche** [comment]
Moved the resolvement issue to the right repo: https://github.com/kg-construct/rml-resources/issues/5

**Comment by DylanVanAssche** [comment]
Please re-open or open a new issue if you find more problems. Thanks!
