### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-io#47]
- [ ] 0002e refers to `rml:targzip` instead of `rml:targz`
- [ ] 0006e refers to `rml:targzip` instead of `rml:targz`
- [ ] 0003 use of relative location of the data dump. Is it by default the location of the mapping file?
- [ ] 0003 refers to `id` in a reference, but there is no `?id` in the SPARQL Query or 0003 should look as follows:

``` 
<#TriplesMap> a rml:TriplesMap;
  rml:logicalSource [ a rml:LogicalSource;
    rml:source <#VoIDSourceAccess>;
    rml:iterator """
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>

    SELECT ?person ?name ?age WHERE {    # HERE IS THE CHANGE
        ?person foaf:name ?name .
        ?person foaf:age ?age .
    }
    """;
    rml:referenceFormulation formats:SPARQL_Results_CSV;
  ];
  rml:subjectMap [ a rml:SubjectMap;
    rml:reference "person";    # HERE IS THE CHANGE
  ];
```

**Comment by DylanVanAssche** [comment]
Fixed!
