### ISSUE TITLE
Small issues with test cases:

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-io#51]
- [x] RMLSTC0004a does not have a reference formulation
- [x] RMLSTC0004b does not have a reference formulation
- [ ] RMLSTC0004c has the wrong reference formulation (`rml:referenceFormulation rml:JSONPath`)
- [ ] RMLSTC0004a wrong `csvw:url` -> should be `file:`

**Comment by DylanVanAssche** [comment]
>  RMLSTC0004a has the wrong reference formulation (rml:referenceFormulation rml:JSONPath)

I think this has a typo, which test-case do you mean? 4a appears twice.

**Comment by chrdebru** [comment]
Yes, I meant 0004c
