### ISSUE TITLE
Small issues with Source 0006x

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-io#57]
- [x] 00006b: the SPARQL query does not contain an `id` variable. Here is a solution:

``` 
    rml:iterator """
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>

    SELECT ?id ?name ?age WHERE {
        ?person foaf:name ?name .
        ?person foaf:age ?age .
        BIND(REPLACE(STR(?person),"http://example.org/", "") AS ?id) .
    }
    """;

``` 

- [x] 0006f misses a reference formulation, but is it a relational database or a CSV file. The mapping seems incomplete.

**Comment by DylanVanAssche** [comment]
>  00006b: the SPARQL query does not contain an id variable. Here is a solution:

We can fix that, thanks to catch it!

>  0006f misses a reference formulation, but is it a relational database or a CSV file. The mapping seems incomplete.

It should be a relational database.

**Comment by DylanVanAssche** [comment]
Fixed, thanks!
