### ISSUE TITLE
VOID vs DCAT targeting?

### ISSUE THREAD

**Issue by VladimirAlexiev** [kg-construct/rml-io#67]
I understand that RML wants to reuse existing vocabularies for targeting:
> An external vocabulary such as DCAT, VoID, SD is allowed here. If a target cannot be accessed with existing vocabulary, a custom vocabulary can be used

The spec gives many examples of targeting `void:Dataset.dataDump` vs `dcat:Dataset.distribution.accessURL`, the first one at https://kg-construct.github.io/rml-io/spec/docs/#target-examples.

But what is the value of this? These examples do the same thing (target a file):
so why confuse users (and indirectly ask developers to do more work) by giving both examples?

**Comment by DylanVanAssche** [comment]
> But what is the value of this

Showing that the specifications are not limited by a specific vocabulary. All these examples are not a _MUST_ in the specification, you can use any specification you want for access.

> so why confuse users (and indirectly ask developers to do more work) by giving both examples?

For the sake of clarity we should indeed just drop VOID. DCAT coverages more.
