### ISSUE TITLE
Targets should give examples of authentication

### ISSUE THREAD

**Issue by VladimirAlexiev** [kg-construct/rml-io#68]
The spec says
> handling an authentication flow may be specific for that specific target. A custom ontology can be used here to describe this authentication flow.

And then https://kg-construct.github.io/rml-io/spec/docs/#target-examples gives examples of:
- SPARQL update <http://example.com/sparql-update>
- Writing to a URL <http://example.org/dcat-access-url>

But a proper SPARQL or HTTP server will require authentication for such writing. So please give some authentication examples.

The following TD examples should refer to https://www.w3.org/2019/wot/security, and use some example Security parameters.

**Comment by DylanVanAssche** [comment]
Good point, we should add more examples with authentication in mind.
