### ISSUE TITLE
define `mqv, d2rq` prefixes

### ISSUE THREAD

**Issue by VladimirAlexiev** [kg-construct/rml-io#69]
The spec uses prefixes `mqv, d2rq` but does not define them.

(https://kg-construct.github.io/rml-io/spec/docs/#overview defines 5 other prefixes used in Target examples)

**Comment by DylanVanAssche** [comment]
Thanks for spotting this, we will add it.

**Comment by DylanVanAssche** [comment]
`mqv` comes from https://www.w3.org/TR/wot-binding-templates/ but the prefix is still not specified.
I will remove these examples from the spec.

**Comment by VladimirAlexiev** [comment]
It's shown in https://www.w3.org/TR/wot-binding-templates/#example-td-with-one-protocol-per-form:
`"mqv": "http://www.example.org/mqtt-binding#"`

Even if that's unofficial/brittle, don't remove the example since it's excellent!
Instead, post a bug against that spec.

**Comment by DylanVanAssche** [comment]
Okay! We can open an issue with them to check if they have plans to even add it :) 
I'm glad it is useful :)

**Comment by DylanVanAssche** [comment]
Moved the tracking of mqv prefix to a separate issue as this issue contains 2 things: mqv and fix for d2rq. The latter is fixed, so closing.
