### ISSUE TITLE
testcase 0002d and 0002e - tarxz and targz files are not actually compressed?

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-io#77]
running `tar --xz -xf Friends.json.tar.xz` in [RMLSTC0002d](https://github.com/kg-construct/rml-io/tree/main/test-cases/RMLSTC0002d)

gives

```shell
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

running `tar xvzf Friends.json.tar.gz` in [RMLSTC0002e](https://github.com/kg-construct/rml-io/tree/main/test-cases/RMLSTC0002e)

gives 

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by DylanVanAssche** [comment]
Recompressed them, should be fine now.
