### ISSUE TITLE
Default iterators for JSON and XML (and maybe other reference formulations)

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-io#87]
For the RML-LV spec it would be useful to have default iterators for other reference formulations (not only for CSV and TSV). 
The default iterator for JSON or XML could be the root of the document. 
Can we have a registry of default iterators per reference formulation in RML-IO?

**Comment by dachafra** [comment]
Is this an issue of [rml-io](https://github.com/kg-construct/rml-io) or [rml-io-registry](https://github.com/kg-construct/rml-io-registry)?

**Comment by elsdvlee** [comment]
[rml-io-registry[(https://github.com/kg-construct/rml-io-registry/issues) indeed. I will move this issues.

**Comment by elsdvlee** [comment]
see [issue #3](https://github.com/kg-construct/rml-io-registry/issues/3)
